backend:
    name: git-gateway
    branch: master

media_folder: "src/assets/images/uploads"
public_folder: "/images/uploads"

collections:
    - name: "pages"
      label: "Pages"
      delete: false
      editor:
        preview: false
      files:
        - name: "home"
          label: "Home Page"
          file: "src/content/home.md"
          delete: false
          fields:
            - {label: "Title", name: "title", widget: "string"}